import {
  BadgeDollarSign,
  File,
  Home,
  Package2,
  Package,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  SquareActivity,
  StoreIcon,
  Truck,
  User2,
  UsersRound,
  Zap,
  CheckCircle2,
  Megaphone,
  Ticket,
  DollarSign,
  BarChart3,
  ClipboardCheck,
} from "lucide-react";

export const navItems = [
  {
    icon: <Home className='w-5 h-5' />,
    title: "Dashboard",
    link: "/dashboard",
    active: true,
    id: "dashboard",
    roles: ["admin", "manager", "moderator"],
  },
  {
    icon: <ShoppingCart className='w-5 h-5' />,
    title: "Orders",
    link: "/order",
    active: true,
    id: "order",
    items: [
      {
        title: "Order Confirmation",
        url: "/order/confirmation",
      },
      {
        title: "Create Order",
        url: "/order/create",
      },
    ],
    roles: ["admin", "manager", "moderator"],
  },
  {
    icon: <CheckCircle2 className='w-5 h-5' />,
    title: "Order Confirmation",
    link: "/order/confirmation",
    active: true,
    id: "order-confirmation",
    roles: ["admin", "manager", "moderator"],
  },
  {
    icon: <Package className='w-5 h-5' />,
    title: "Packages",
    link: "/packages",
    active: true,
    id: "Package",
    roles: ["admin", "manager", "moderator"],
  },
  {
    icon: <Truck className='w-5 h-5' />,
    title: "Delivery",
    link: "/delivery",
    active: true,
    id: "delivery",
    roles: ["admin"],
  },
  {
    icon: <Shirt className='w-5 h-5' />,
    title: "Products",
    link: "/products",
    active: true,
    id: "product",
    items: [
      {
        title: "Add Product",
        url: "/products/create",
      },
      {
        title: "Product Analytics",
        url: "/products/analytics",
      },
    ],
    roles: ["admin", "manager"],
  },
  {
    icon: <Package2 className='w-5 h-5' />,
    title: "Category",
    link: "/category",
    active: true,
    id: "category",
    roles: ["admin", "manager"],
  },
  {
    icon: <Zap className='w-5 h-5' />,
    title: "Campaign",
    link: "/campaign",
    active: true,
    id: "campaign",
    roles: ["admin", "manager"],
  },
  {
    icon: <ShoppingBag className='w-5 h-5' />,
    title: "Purchase",
    link: "/purchase-order/list",
    active: true,
    id: "purchaseorder",
    roles: ["admin", "manager"],
  },
  {
    icon: <BadgeDollarSign className='w-5 h-5' />,
    title: "Transactions",
    link: "/transactions",
    active: false,
    id: "transaction",
    roles: ["admin"],
  },
  {
    icon: <File className='w-5 h-5' />,
    title: "Reports",
    link: "/reports",
    active: true,
    id: "report",
    roles: ["admin"],
    items: [
      {
        title: "Report Analytics",
        url: "/reports-v2",
      },
    ],
  },
  {
    icon: <BarChart3 className='w-5 h-5' />,
    title: "Daily Reports",
    link: "/daily-reports",
    active: true,
    id: "DailyReport",
    roles: ["admin"],
  },
  {
    icon: <ClipboardCheck className='w-5 h-5' />,
    title: "Operation Requests",
    link: "/operation-requests",
    active: true,
    id: "OperationRequest",
    roles: ["admin", "manager"],
  },

  {
    icon: <StoreIcon className='w-5 h-5' />,
    title: "Stores",
    link: "/stores",
    active: true,
    id: "reservestore",
    roles: ["admin", "manager"],
  },
  {
    icon: <UsersRound className='w-5 h-5' />,
    title: "Users",
    link: "/users",
    active: true,
    id: "user",
    roles: ["admin"],
  },
  {
    icon: <ShieldCheck className='w-5 h-5' />,
    title: "Roles",
    link: "/roles",
    active: true,
    id: "role",
    roles: ["admin", "manager"],
  },
  {
    icon: <User2 className='w-5 h-5' />,
    title: "Customers",
    link: "/customers/analytics",
    active: true,
    id: "customer",
    items: [
      {
        title: "Customer Analytics",
        url: "/customers/analytics",
      },
    ],
    roles: ["admin", "manager"],
  },
  {
    icon: <SquareActivity className='w-5 h-5' />,
    title: "AUDIT",
    link: "/audit",
    active: true,
    id: "audit",
    roles: ["admin"],
  },
  {
    icon: <Megaphone className='w-5 h-5' />,
    title: "Bulk Communication",
    link: "/bulk-communication/sms",
    active: true,
    id: "bulkcommunication",
    items: [
      {
        title: "Bulk SMS",
        url: "/bulk-communication/sms",
      },
      {
        title: "Bulk Email",
        url: "/bulk-communication/email",
      },
    ],
    roles: ["admin", "manager"],
  },
  {
    icon: <Ticket className='w-5 h-5' />,
    title: "Coupons",
    link: "/coupons",
    active: true,
    id: "coupon",
    items: [
      {
        title: "Global Coupons",
        url: "/coupons/global",
      },
      {
        title: "Customer Coupons",
        url: "/coupons/customer",
      },
      {
        title: "Analytics",
        url: "/coupons/analytics",
      },
    ],
    roles: ["admin", "manager"],
  },
  {
    icon: <DollarSign className='w-5 h-5' />,
    title: "Commission",
    link: "/commission",
    active: true,
    id: "commission",
    roles: ["admin", "manager"],
  },
  // {
  //   icon: <MessageCircle className='w-5 h-5' />,
  //   title: "Live Chat",
  //   link: "/chat",
  //   active: true,
  //   id: "chat",
  //   roles: ["admin", "manager", "moderator"],
  // },
];
