export const pagePermissions: Record<string, string[]> = {
  Dashboard: ["view"],
  Order: [
    "view",
    "create",
    "edit",
    "delete",
    "modify",
    "view_details",
    "bulk_action",
    "documents",
  ],
  OrderConfirmation: ["view", "confirm", "cancel"],
  Product: ["view", "create", "edit", "delete", "summary", "analytics"],
  Category: ["view", "create", "edit", "delete"],
  Campaign: ["view", "create", "edit", "delete"],
  PurchaseOrder: ["view", "create", "edit", "delete"],
  Transaction: ["view", "edit", "delete"],
  ReserveStore: ["view", "create", "edit", "delete", "store_access"],
  ReserveRecord: ["view", "create", "edit", "delete"],
  User: ["view", "create", "edit", "delete"],
  Role: ["view", "create", "edit", "delete"],
  Report: ["view", "create", "edit", "delete", "download"],
  Chat: ["view", "reply", "attend", "manage", "delete"],
  Settings: ["view", "edit", "jobs_management"],
  Delivery: ["view", "edit", "delete", "create"],
  Notifications: ["view", "edit", "delete", "create"],
  Audit: ["view"],
  Package: ["view", "create", "edit", "delete"],
  BulkCommunication: ["view", "create", "delete", "cancel"],
  Customer: ["view", "edit"],
  Coupon: ["view", "create", "edit", "delete", "assign", "analytics"],
};
